file_format: '1'
id: skeletyl
name: Skeletyl
type: shield
url: https://github.com/Bastardkb/Skeletyl
requires: [nice_nano_v2]
features:
  - keys
  - studio
siblings:
  - skeletyl_left
  - skeletyl_right
